"""Declarative Dagr library for the fractal-forest IPC demo.

One SharedBuffer, `Forest`, holds the branch geometry of an animated fractal
forest as struct-of-arrays. It uses the **`double_buffer`** concurrency strategy:
the producer fills an off-screen slot and publishes it with a single atomic
exchange; the consumer always latches the newest completed frame and never tears or
retries. The control word + three node-sized slots all live in the shared region, so
a producer in one language/process and a consumer in another agree on the bytes with
zero marshalling.

Two targets, generated by the Dagr CLI (`dagr build --schema forest_schema.py`):

  Mojo → this dir/            ForestSharedBuffer.mojo   (the GPU producer's overlay)
  Odin → this dir/forest_sb/  forest_sb.odin            (the raylib renderer's overlay)

The Dagr CLI is in private beta; the generated overlays are committed to this repo
so the demo builds and runs without it. See the README.

Geometry (all arrays are 64-byte aligned so GPU/SIMD writes land on aligned
addresses; f32 for the endpoints the GPU computes, u8 for per-branch depth which
the renderer maps to colour + thickness):

  count : u32        live segment count
  frame : u32        frame counter (nice for the on-screen HUD)
  x0,y0 : [f32]      segment start points
  x1,y1 : [f32]      segment end points
  depth : [u8]       branch depth 0..TREE_DEPTH (0 = trunk)
"""
import os

from dagr_dsl import t, required, Node, SharedBuffer, aligned, cap
from dagr_config import Library, Mojo, Odin

HERE = os.path.dirname(os.path.abspath(__file__))

# A forest of TREES fractal trees, each a full binary tree of depth TREE_DEPTH.
# Branches per tree = 2**TREE_DEPTH - 1; capacity is rounded up to a multiple of 64
# (matches the aligned(64) regions and leaves headroom).
TREES = 3
TREE_DEPTH = 12                       # 4095 branches/tree
SEG_CAP = 12288                       # >= TREES*(2**TREE_DEPTH - 1) = 12285, /64 = 192

# The forest's tunable parameters + the shared-region path. Declared as SharedBuffer
# `constants` below, they are emitted as compile-time constants into BOTH generated
# overlays (Mojo and Odin) — so the producer and the renderer read one source of
# truth instead of each hard-coding their own copy.
WORLD_W = 1280.0                      # virtual canvas the producer draws into / window size
WORLD_H = 800.0
L0 = 150.0                            # trunk length (px)
RATIO = 0.74                         # child / parent branch length
THETA = 0.40                         # branch half-angle (rad)
WIND = 0.06                          # sway amplitude (rad / level)
SPEED = 1.3                          # sway temporal frequency
PATH = "/tmp/dagr_forest_ipc.bin"    # the mmap'd region both processes open

Forest = SharedBuffer("Forest", root_type="Forest", concurrency="double_buffer",
    constants={
        "TREES": TREES, "TREE_DEPTH": TREE_DEPTH, "SEG_CAP": SEG_CAP,
        "WORLD_W": WORLD_W, "WORLD_H": WORLD_H,
        "L0": L0, "RATIO": RATIO, "THETA": THETA, "WIND": WIND, "SPEED": SPEED,
        "PATH": PATH,
    },
    node_types=[
    Node("Forest", frozen=True, fields=[
        "count" >> t.u32 >> required,
        "frame" >> t.u32 >> required,
        "x0" >> t.f32.array >> aligned(64) >> cap(SEG_CAP) >> required,
        "y0" >> t.f32.array >> aligned(64) >> cap(SEG_CAP) >> required,
        "x1" >> t.f32.array >> aligned(64) >> cap(SEG_CAP) >> required,
        "y1" >> t.f32.array >> aligned(64) >> cap(SEG_CAP) >> required,
        "depth" >> t.u8.array >> aligned(64) >> cap(SEG_CAP) >> required,
    ]),
])

library = Library("ForestOverlay", [Forest], targets=[
    Mojo(out=HERE),
    Odin(out=HERE),
])
