# GENERATED by the Dagr CLI (`dagr build`) — do not edit.
# SharedBuffer 'Forest' (concurrency=double_buffer) — fixed-layout overlay.
# Standalone overlay: no dependency on the graph reader.

from std.memory import unsafe_memset_zero
from std.memory.alloc import unsafe_alloc

from std.atomic import Atomic, fence

comptime BYTE_SIZE = 626944
comptime REGION_ALIGN = 64
comptime ROOT_OFFSET = 64

@fieldwise_init
struct Forest(Copyable, Movable):
    var ptr: Pointer[UInt8, MutUntrackedOrigin]
    var base: Int
    @staticmethod
    @always_inline
    def wrap(ptr: Pointer[UInt8, MutUntrackedOrigin]) -> Forest:
        return Forest(ptr, ROOT_OFFSET)
    @always_inline
    def count(self) -> UInt32:
        return (self.ptr.unsafe_offset(self.base + 208896)).unsafe_bitcast[UInt32]().unsafe_load[alignment=1]()
    @always_inline
    def set_count(self, v: UInt32):
        (self.ptr.unsafe_offset(self.base + 208896)).unsafe_bitcast[UInt32]().unsafe_store[alignment=1](v)
    @always_inline
    def frame(self) -> UInt32:
        return (self.ptr.unsafe_offset(self.base + 208900)).unsafe_bitcast[UInt32]().unsafe_load[alignment=1]()
    @always_inline
    def set_frame(self, v: UInt32):
        (self.ptr.unsafe_offset(self.base + 208900)).unsafe_bitcast[UInt32]().unsafe_store[alignment=1](v)
    @always_inline
    def x0_len(self) -> UInt16:
        return (self.ptr.unsafe_offset(self.base + 208904)).unsafe_bitcast[UInt16]().unsafe_load[alignment=1]()
    @always_inline
    def set_x0_len(self, n: UInt16) raises:
        if Int(n) > 12288:
            raise Error("x0 length exceeds capacity 12288")
        (self.ptr.unsafe_offset(self.base + 208904)).unsafe_bitcast[UInt16]().unsafe_store[alignment=1](n)
    @always_inline
    def x0(self, i: Int) raises -> Float32:
        if i < 0 or i >= 12288:
            raise Error("x0: index out of range [0, 12288)")
        return (self.ptr.unsafe_offset(self.base + 0 + i * 4)).unsafe_bitcast[Float32]().unsafe_load[alignment=1]()
    @always_inline
    def x0_unchecked(self, i: Int) -> Float32:
        return (self.ptr.unsafe_offset(self.base + 0 + i * 4)).unsafe_bitcast[Float32]().unsafe_load[alignment=1]()
    @always_inline
    def x0_at[i: Int](self) -> Float32:
        comptime assert i >= 0 and i < 12288, "x0: index out of range [0, 12288)"
        return (self.ptr.unsafe_offset(self.base + 0 + i * 4)).unsafe_bitcast[Float32]().unsafe_load[alignment=1]()
    @always_inline
    def set_x0(self, i: Int, v: Float32) raises:
        if i < 0 or i >= 12288:
            raise Error("x0: index out of range [0, 12288)")
        (self.ptr.unsafe_offset(self.base + 0 + i * 4)).unsafe_bitcast[Float32]().unsafe_store[alignment=1](v)
    @always_inline
    def set_x0_unchecked(self, i: Int, v: Float32):
        (self.ptr.unsafe_offset(self.base + 0 + i * 4)).unsafe_bitcast[Float32]().unsafe_store[alignment=1](v)
    @always_inline
    def set_x0_at[i: Int](self, v: Float32):
        comptime assert i >= 0 and i < 12288, "x0: index out of range [0, 12288)"
        (self.ptr.unsafe_offset(self.base + 0 + i * 4)).unsafe_bitcast[Float32]().unsafe_store[alignment=1](v)
    @always_inline
    def x0_ptr(self) -> Pointer[Float32, MutUntrackedOrigin]:
        # 64-byte aligned typed pointer to the element region (SIMD-ready)
        return (self.ptr.unsafe_offset(self.base + 0)).unsafe_bitcast[Float32]()
    @always_inline
    def x0_load[w: Int](self, i: Int) raises -> SIMD[DType.float32, w]:
        if i < 0 or i + w > 12288:
            raise Error("x0: SIMD range [i, i+w) out of bounds [0, 12288)")
        return (self.x0_ptr().unsafe_offset(i)).unsafe_load[width=w, alignment=64]()
    @always_inline
    def x0_load_unchecked[w: Int](self, i: Int) -> SIMD[DType.float32, w]:
        return (self.x0_ptr().unsafe_offset(i)).unsafe_load[width=w, alignment=64]()
    @always_inline
    def x0_store[w: Int](self, i: Int, v: SIMD[DType.float32, w]) raises:
        if i < 0 or i + w > 12288:
            raise Error("x0: SIMD range [i, i+w) out of bounds [0, 12288)")
        (self.x0_ptr().unsafe_offset(i)).unsafe_store[width=w, alignment=64](v)
    @always_inline
    def x0_store_unchecked[w: Int](self, i: Int, v: SIMD[DType.float32, w]):
        (self.x0_ptr().unsafe_offset(i)).unsafe_store[width=w, alignment=64](v)
    @always_inline
    def y0_len(self) -> UInt16:
        return (self.ptr.unsafe_offset(self.base + 208906)).unsafe_bitcast[UInt16]().unsafe_load[alignment=1]()
    @always_inline
    def set_y0_len(self, n: UInt16) raises:
        if Int(n) > 12288:
            raise Error("y0 length exceeds capacity 12288")
        (self.ptr.unsafe_offset(self.base + 208906)).unsafe_bitcast[UInt16]().unsafe_store[alignment=1](n)
    @always_inline
    def y0(self, i: Int) raises -> Float32:
        if i < 0 or i >= 12288:
            raise Error("y0: index out of range [0, 12288)")
        return (self.ptr.unsafe_offset(self.base + 49152 + i * 4)).unsafe_bitcast[Float32]().unsafe_load[alignment=1]()
    @always_inline
    def y0_unchecked(self, i: Int) -> Float32:
        return (self.ptr.unsafe_offset(self.base + 49152 + i * 4)).unsafe_bitcast[Float32]().unsafe_load[alignment=1]()
    @always_inline
    def y0_at[i: Int](self) -> Float32:
        comptime assert i >= 0 and i < 12288, "y0: index out of range [0, 12288)"
        return (self.ptr.unsafe_offset(self.base + 49152 + i * 4)).unsafe_bitcast[Float32]().unsafe_load[alignment=1]()
    @always_inline
    def set_y0(self, i: Int, v: Float32) raises:
        if i < 0 or i >= 12288:
            raise Error("y0: index out of range [0, 12288)")
        (self.ptr.unsafe_offset(self.base + 49152 + i * 4)).unsafe_bitcast[Float32]().unsafe_store[alignment=1](v)
    @always_inline
    def set_y0_unchecked(self, i: Int, v: Float32):
        (self.ptr.unsafe_offset(self.base + 49152 + i * 4)).unsafe_bitcast[Float32]().unsafe_store[alignment=1](v)
    @always_inline
    def set_y0_at[i: Int](self, v: Float32):
        comptime assert i >= 0 and i < 12288, "y0: index out of range [0, 12288)"
        (self.ptr.unsafe_offset(self.base + 49152 + i * 4)).unsafe_bitcast[Float32]().unsafe_store[alignment=1](v)
    @always_inline
    def y0_ptr(self) -> Pointer[Float32, MutUntrackedOrigin]:
        # 64-byte aligned typed pointer to the element region (SIMD-ready)
        return (self.ptr.unsafe_offset(self.base + 49152)).unsafe_bitcast[Float32]()
    @always_inline
    def y0_load[w: Int](self, i: Int) raises -> SIMD[DType.float32, w]:
        if i < 0 or i + w > 12288:
            raise Error("y0: SIMD range [i, i+w) out of bounds [0, 12288)")
        return (self.y0_ptr().unsafe_offset(i)).unsafe_load[width=w, alignment=64]()
    @always_inline
    def y0_load_unchecked[w: Int](self, i: Int) -> SIMD[DType.float32, w]:
        return (self.y0_ptr().unsafe_offset(i)).unsafe_load[width=w, alignment=64]()
    @always_inline
    def y0_store[w: Int](self, i: Int, v: SIMD[DType.float32, w]) raises:
        if i < 0 or i + w > 12288:
            raise Error("y0: SIMD range [i, i+w) out of bounds [0, 12288)")
        (self.y0_ptr().unsafe_offset(i)).unsafe_store[width=w, alignment=64](v)
    @always_inline
    def y0_store_unchecked[w: Int](self, i: Int, v: SIMD[DType.float32, w]):
        (self.y0_ptr().unsafe_offset(i)).unsafe_store[width=w, alignment=64](v)
    @always_inline
    def x1_len(self) -> UInt16:
        return (self.ptr.unsafe_offset(self.base + 208908)).unsafe_bitcast[UInt16]().unsafe_load[alignment=1]()
    @always_inline
    def set_x1_len(self, n: UInt16) raises:
        if Int(n) > 12288:
            raise Error("x1 length exceeds capacity 12288")
        (self.ptr.unsafe_offset(self.base + 208908)).unsafe_bitcast[UInt16]().unsafe_store[alignment=1](n)
    @always_inline
    def x1(self, i: Int) raises -> Float32:
        if i < 0 or i >= 12288:
            raise Error("x1: index out of range [0, 12288)")
        return (self.ptr.unsafe_offset(self.base + 98304 + i * 4)).unsafe_bitcast[Float32]().unsafe_load[alignment=1]()
    @always_inline
    def x1_unchecked(self, i: Int) -> Float32:
        return (self.ptr.unsafe_offset(self.base + 98304 + i * 4)).unsafe_bitcast[Float32]().unsafe_load[alignment=1]()
    @always_inline
    def x1_at[i: Int](self) -> Float32:
        comptime assert i >= 0 and i < 12288, "x1: index out of range [0, 12288)"
        return (self.ptr.unsafe_offset(self.base + 98304 + i * 4)).unsafe_bitcast[Float32]().unsafe_load[alignment=1]()
    @always_inline
    def set_x1(self, i: Int, v: Float32) raises:
        if i < 0 or i >= 12288:
            raise Error("x1: index out of range [0, 12288)")
        (self.ptr.unsafe_offset(self.base + 98304 + i * 4)).unsafe_bitcast[Float32]().unsafe_store[alignment=1](v)
    @always_inline
    def set_x1_unchecked(self, i: Int, v: Float32):
        (self.ptr.unsafe_offset(self.base + 98304 + i * 4)).unsafe_bitcast[Float32]().unsafe_store[alignment=1](v)
    @always_inline
    def set_x1_at[i: Int](self, v: Float32):
        comptime assert i >= 0 and i < 12288, "x1: index out of range [0, 12288)"
        (self.ptr.unsafe_offset(self.base + 98304 + i * 4)).unsafe_bitcast[Float32]().unsafe_store[alignment=1](v)
    @always_inline
    def x1_ptr(self) -> Pointer[Float32, MutUntrackedOrigin]:
        # 64-byte aligned typed pointer to the element region (SIMD-ready)
        return (self.ptr.unsafe_offset(self.base + 98304)).unsafe_bitcast[Float32]()
    @always_inline
    def x1_load[w: Int](self, i: Int) raises -> SIMD[DType.float32, w]:
        if i < 0 or i + w > 12288:
            raise Error("x1: SIMD range [i, i+w) out of bounds [0, 12288)")
        return (self.x1_ptr().unsafe_offset(i)).unsafe_load[width=w, alignment=64]()
    @always_inline
    def x1_load_unchecked[w: Int](self, i: Int) -> SIMD[DType.float32, w]:
        return (self.x1_ptr().unsafe_offset(i)).unsafe_load[width=w, alignment=64]()
    @always_inline
    def x1_store[w: Int](self, i: Int, v: SIMD[DType.float32, w]) raises:
        if i < 0 or i + w > 12288:
            raise Error("x1: SIMD range [i, i+w) out of bounds [0, 12288)")
        (self.x1_ptr().unsafe_offset(i)).unsafe_store[width=w, alignment=64](v)
    @always_inline
    def x1_store_unchecked[w: Int](self, i: Int, v: SIMD[DType.float32, w]):
        (self.x1_ptr().unsafe_offset(i)).unsafe_store[width=w, alignment=64](v)
    @always_inline
    def y1_len(self) -> UInt16:
        return (self.ptr.unsafe_offset(self.base + 208910)).unsafe_bitcast[UInt16]().unsafe_load[alignment=1]()
    @always_inline
    def set_y1_len(self, n: UInt16) raises:
        if Int(n) > 12288:
            raise Error("y1 length exceeds capacity 12288")
        (self.ptr.unsafe_offset(self.base + 208910)).unsafe_bitcast[UInt16]().unsafe_store[alignment=1](n)
    @always_inline
    def y1(self, i: Int) raises -> Float32:
        if i < 0 or i >= 12288:
            raise Error("y1: index out of range [0, 12288)")
        return (self.ptr.unsafe_offset(self.base + 147456 + i * 4)).unsafe_bitcast[Float32]().unsafe_load[alignment=1]()
    @always_inline
    def y1_unchecked(self, i: Int) -> Float32:
        return (self.ptr.unsafe_offset(self.base + 147456 + i * 4)).unsafe_bitcast[Float32]().unsafe_load[alignment=1]()
    @always_inline
    def y1_at[i: Int](self) -> Float32:
        comptime assert i >= 0 and i < 12288, "y1: index out of range [0, 12288)"
        return (self.ptr.unsafe_offset(self.base + 147456 + i * 4)).unsafe_bitcast[Float32]().unsafe_load[alignment=1]()
    @always_inline
    def set_y1(self, i: Int, v: Float32) raises:
        if i < 0 or i >= 12288:
            raise Error("y1: index out of range [0, 12288)")
        (self.ptr.unsafe_offset(self.base + 147456 + i * 4)).unsafe_bitcast[Float32]().unsafe_store[alignment=1](v)
    @always_inline
    def set_y1_unchecked(self, i: Int, v: Float32):
        (self.ptr.unsafe_offset(self.base + 147456 + i * 4)).unsafe_bitcast[Float32]().unsafe_store[alignment=1](v)
    @always_inline
    def set_y1_at[i: Int](self, v: Float32):
        comptime assert i >= 0 and i < 12288, "y1: index out of range [0, 12288)"
        (self.ptr.unsafe_offset(self.base + 147456 + i * 4)).unsafe_bitcast[Float32]().unsafe_store[alignment=1](v)
    @always_inline
    def y1_ptr(self) -> Pointer[Float32, MutUntrackedOrigin]:
        # 64-byte aligned typed pointer to the element region (SIMD-ready)
        return (self.ptr.unsafe_offset(self.base + 147456)).unsafe_bitcast[Float32]()
    @always_inline
    def y1_load[w: Int](self, i: Int) raises -> SIMD[DType.float32, w]:
        if i < 0 or i + w > 12288:
            raise Error("y1: SIMD range [i, i+w) out of bounds [0, 12288)")
        return (self.y1_ptr().unsafe_offset(i)).unsafe_load[width=w, alignment=64]()
    @always_inline
    def y1_load_unchecked[w: Int](self, i: Int) -> SIMD[DType.float32, w]:
        return (self.y1_ptr().unsafe_offset(i)).unsafe_load[width=w, alignment=64]()
    @always_inline
    def y1_store[w: Int](self, i: Int, v: SIMD[DType.float32, w]) raises:
        if i < 0 or i + w > 12288:
            raise Error("y1: SIMD range [i, i+w) out of bounds [0, 12288)")
        (self.y1_ptr().unsafe_offset(i)).unsafe_store[width=w, alignment=64](v)
    @always_inline
    def y1_store_unchecked[w: Int](self, i: Int, v: SIMD[DType.float32, w]):
        (self.y1_ptr().unsafe_offset(i)).unsafe_store[width=w, alignment=64](v)
    @always_inline
    def depth_len(self) -> UInt16:
        return (self.ptr.unsafe_offset(self.base + 208912)).unsafe_bitcast[UInt16]().unsafe_load[alignment=1]()
    @always_inline
    def set_depth_len(self, n: UInt16) raises:
        if Int(n) > 12288:
            raise Error("depth length exceeds capacity 12288")
        (self.ptr.unsafe_offset(self.base + 208912)).unsafe_bitcast[UInt16]().unsafe_store[alignment=1](n)
    @always_inline
    def depth(self, i: Int) raises -> UInt8:
        if i < 0 or i >= 12288:
            raise Error("depth: index out of range [0, 12288)")
        return (self.ptr.unsafe_offset(self.base + 196608 + i * 1)).unsafe_bitcast[UInt8]().unsafe_load[alignment=1]()
    @always_inline
    def depth_unchecked(self, i: Int) -> UInt8:
        return (self.ptr.unsafe_offset(self.base + 196608 + i * 1)).unsafe_bitcast[UInt8]().unsafe_load[alignment=1]()
    @always_inline
    def depth_at[i: Int](self) -> UInt8:
        comptime assert i >= 0 and i < 12288, "depth: index out of range [0, 12288)"
        return (self.ptr.unsafe_offset(self.base + 196608 + i * 1)).unsafe_bitcast[UInt8]().unsafe_load[alignment=1]()
    @always_inline
    def set_depth(self, i: Int, v: UInt8) raises:
        if i < 0 or i >= 12288:
            raise Error("depth: index out of range [0, 12288)")
        (self.ptr.unsafe_offset(self.base + 196608 + i * 1)).unsafe_bitcast[UInt8]().unsafe_store[alignment=1](v)
    @always_inline
    def set_depth_unchecked(self, i: Int, v: UInt8):
        (self.ptr.unsafe_offset(self.base + 196608 + i * 1)).unsafe_bitcast[UInt8]().unsafe_store[alignment=1](v)
    @always_inline
    def set_depth_at[i: Int](self, v: UInt8):
        comptime assert i >= 0 and i < 12288, "depth: index out of range [0, 12288)"
        (self.ptr.unsafe_offset(self.base + 196608 + i * 1)).unsafe_bitcast[UInt8]().unsafe_store[alignment=1](v)
    @always_inline
    def depth_ptr(self) -> Pointer[UInt8, MutUntrackedOrigin]:
        # 64-byte aligned typed pointer to the element region (SIMD-ready)
        return (self.ptr.unsafe_offset(self.base + 196608)).unsafe_bitcast[UInt8]()
    @always_inline
    def depth_load[w: Int](self, i: Int) raises -> SIMD[DType.uint8, w]:
        if i < 0 or i + w > 12288:
            raise Error("depth: SIMD range [i, i+w) out of bounds [0, 12288)")
        return (self.depth_ptr().unsafe_offset(i)).unsafe_load[width=w, alignment=64]()
    @always_inline
    def depth_load_unchecked[w: Int](self, i: Int) -> SIMD[DType.uint8, w]:
        return (self.depth_ptr().unsafe_offset(i)).unsafe_load[width=w, alignment=64]()
    @always_inline
    def depth_store[w: Int](self, i: Int, v: SIMD[DType.uint8, w]) raises:
        if i < 0 or i + w > 12288:
            raise Error("depth: SIMD range [i, i+w) out of bounds [0, 12288)")
        (self.depth_ptr().unsafe_offset(i)).unsafe_store[width=w, alignment=64](v)
    @always_inline
    def depth_store_unchecked[w: Int](self, i: Int, v: SIMD[DType.uint8, w]):
        (self.depth_ptr().unsafe_offset(i)).unsafe_store[width=w, alignment=64](v)

def allocate() -> Pointer[UInt8, MutUntrackedOrigin]:
    var p = unsafe_alloc[UInt8](BYTE_SIZE)
    unsafe_memset_zero(p, BYTE_SIZE)
    return p

comptime NODE_SIZE = 208960

@fieldwise_init
struct Producer(Copyable, Movable, ImplicitlyCopyable):
    var ptr: Pointer[UInt8, MutUntrackedOrigin]
    var input: UInt32
    @staticmethod
    @always_inline
    def from_raw(ptr: Pointer[UInt8, MutUntrackedOrigin]) -> Producer:
        return Producer(ptr, UInt32(1))
    @always_inline
    def _ctrl(self) -> Pointer[UInt32, MutUntrackedOrigin]:
        return (self.ptr.unsafe_offset(0)).unsafe_bitcast[UInt32]()
    @always_inline
    def write_slot(self) -> Forest:
        return Forest(self.ptr, ROOT_OFFSET + Int(self.input) * NODE_SIZE)
    @always_inline
    def commit(mut self):
        var old = Atomic._xchg(self._ctrl(), (self.input << 1) | UInt32(1))
        self.input = (old >> 1) & UInt32(3)
    @always_inline
    def free(self):
        self.ptr.unsafe_free()

@fieldwise_init
struct Consumer(Copyable, Movable, ImplicitlyCopyable):
    var ptr: Pointer[UInt8, MutUntrackedOrigin]
    var output: UInt32
    @staticmethod
    @always_inline
    def from_raw(ptr: Pointer[UInt8, MutUntrackedOrigin]) -> Consumer:
        return Consumer(ptr, UInt32(2))
    @always_inline
    def _ctrl(self) -> Pointer[UInt32, MutUntrackedOrigin]:
        return (self.ptr.unsafe_offset(0)).unsafe_bitcast[UInt32]()
    @always_inline
    def has_new(self) -> Bool:
        return (Atomic.load(self._ctrl()) & UInt32(1)) != 0
    @always_inline
    def read(mut self) -> Forest:
        if (Atomic.load(self._ctrl()) & UInt32(1)) != 0:
            var old = Atomic._xchg(self._ctrl(), self.output << 1)
            self.output = (old >> 1) & UInt32(3)
        return Forest(self.ptr, ROOT_OFFSET + Int(self.output) * NODE_SIZE)

def double_buffer() -> Tuple[Producer, Consumer]:
    var p = allocate()
    return (Producer(p, UInt32(1)), Consumer(p, UInt32(2)))
