// GENERATED by the Dagr CLI (`dagr build`) — do not edit.
// SharedBuffer 'Forest' (concurrency=double_buffer) — fixed-layout overlay.
// Standalone overlay: no dependency on the graph reader.
package forest_sb

import "core:mem"
import "base:intrinsics"

BYTE_SIZE :: 626944
REGION_ALIGN :: 64
ROOT_OFFSET :: 64
// Schema constants (pure API — not stored in the buffer).
TREES :: 3
TREE_DEPTH :: 12
SEG_CAP :: 12288
WORLD_W :: 1280.0
WORLD_H :: 800.0
L0 :: 150.0
RATIO :: 0.74
THETA :: 0.4
WIND :: 0.06
SPEED :: 1.3
PATH :: "/tmp/dagr_forest_ipc.bin"

// bf16 has no native Odin type: stored as u16 bits, API type is f32.
_bf16_to_f32 :: proc(b: u16) -> f32 { return transmute(f32)(u32(b) << 16) }
_f32_to_bf16 :: proc(x: f32) -> u16 {
	bits := transmute(u32)x
	rounding := u32(0x7FFF) + ((bits >> 16) & 1)  // round to nearest even
	return u16((bits + rounding) >> 16)
}

Forest :: struct { data: [^]u8, base: int }
wrap :: proc(p: [^]u8) -> Forest { return Forest{data = p, base = ROOT_OFFSET} }
forest_count :: proc(o: Forest) -> u32 { return u32(intrinsics.unaligned_load((^u32le)(&o.data[o.base + 208896]))) }
set_forest_count :: proc(o: Forest, v: u32) { intrinsics.unaligned_store((^u32le)(&o.data[o.base + 208896]), u32le(v)) }
forest_frame :: proc(o: Forest) -> u32 { return u32(intrinsics.unaligned_load((^u32le)(&o.data[o.base + 208900]))) }
set_forest_frame :: proc(o: Forest, v: u32) { intrinsics.unaligned_store((^u32le)(&o.data[o.base + 208900]), u32le(v)) }
forest_x0_len :: proc(o: Forest) -> u16 { return u16(intrinsics.unaligned_load((^u16le)(&o.data[o.base + 208904]))) }
set_forest_x0_len :: proc(o: Forest, n: u16) {
	assert(int(n) <= 12288, "forest_x0 length exceeds capacity 12288")
	intrinsics.unaligned_store((^u16le)(&o.data[o.base + 208904]), u16le(n))
}
forest_x0 :: proc(o: Forest, i: int) -> f32 {
	assert(i >= 0 && i < 12288, "forest_x0: index out of range [0, 12288)")
	return f32(intrinsics.unaligned_load((^f32le)(&o.data[o.base + 0 + i * 4])))
}
set_forest_x0 :: proc(o: Forest, i: int, v: f32) {
	assert(i >= 0 && i < 12288, "forest_x0: index out of range [0, 12288)")
	intrinsics.unaligned_store((^f32le)(&o.data[o.base + 0 + i * 4]), f32le(v))
}
forest_y0_len :: proc(o: Forest) -> u16 { return u16(intrinsics.unaligned_load((^u16le)(&o.data[o.base + 208906]))) }
set_forest_y0_len :: proc(o: Forest, n: u16) {
	assert(int(n) <= 12288, "forest_y0 length exceeds capacity 12288")
	intrinsics.unaligned_store((^u16le)(&o.data[o.base + 208906]), u16le(n))
}
forest_y0 :: proc(o: Forest, i: int) -> f32 {
	assert(i >= 0 && i < 12288, "forest_y0: index out of range [0, 12288)")
	return f32(intrinsics.unaligned_load((^f32le)(&o.data[o.base + 49152 + i * 4])))
}
set_forest_y0 :: proc(o: Forest, i: int, v: f32) {
	assert(i >= 0 && i < 12288, "forest_y0: index out of range [0, 12288)")
	intrinsics.unaligned_store((^f32le)(&o.data[o.base + 49152 + i * 4]), f32le(v))
}
forest_x1_len :: proc(o: Forest) -> u16 { return u16(intrinsics.unaligned_load((^u16le)(&o.data[o.base + 208908]))) }
set_forest_x1_len :: proc(o: Forest, n: u16) {
	assert(int(n) <= 12288, "forest_x1 length exceeds capacity 12288")
	intrinsics.unaligned_store((^u16le)(&o.data[o.base + 208908]), u16le(n))
}
forest_x1 :: proc(o: Forest, i: int) -> f32 {
	assert(i >= 0 && i < 12288, "forest_x1: index out of range [0, 12288)")
	return f32(intrinsics.unaligned_load((^f32le)(&o.data[o.base + 98304 + i * 4])))
}
set_forest_x1 :: proc(o: Forest, i: int, v: f32) {
	assert(i >= 0 && i < 12288, "forest_x1: index out of range [0, 12288)")
	intrinsics.unaligned_store((^f32le)(&o.data[o.base + 98304 + i * 4]), f32le(v))
}
forest_y1_len :: proc(o: Forest) -> u16 { return u16(intrinsics.unaligned_load((^u16le)(&o.data[o.base + 208910]))) }
set_forest_y1_len :: proc(o: Forest, n: u16) {
	assert(int(n) <= 12288, "forest_y1 length exceeds capacity 12288")
	intrinsics.unaligned_store((^u16le)(&o.data[o.base + 208910]), u16le(n))
}
forest_y1 :: proc(o: Forest, i: int) -> f32 {
	assert(i >= 0 && i < 12288, "forest_y1: index out of range [0, 12288)")
	return f32(intrinsics.unaligned_load((^f32le)(&o.data[o.base + 147456 + i * 4])))
}
set_forest_y1 :: proc(o: Forest, i: int, v: f32) {
	assert(i >= 0 && i < 12288, "forest_y1: index out of range [0, 12288)")
	intrinsics.unaligned_store((^f32le)(&o.data[o.base + 147456 + i * 4]), f32le(v))
}
forest_depth_len :: proc(o: Forest) -> u16 { return u16(intrinsics.unaligned_load((^u16le)(&o.data[o.base + 208912]))) }
set_forest_depth_len :: proc(o: Forest, n: u16) {
	assert(int(n) <= 12288, "forest_depth length exceeds capacity 12288")
	intrinsics.unaligned_store((^u16le)(&o.data[o.base + 208912]), u16le(n))
}
forest_depth :: proc(o: Forest, i: int) -> u8 {
	assert(i >= 0 && i < 12288, "forest_depth: index out of range [0, 12288)")
	return u8(intrinsics.unaligned_load((^u8)(&o.data[o.base + 196608 + i * 1])))
}
set_forest_depth :: proc(o: Forest, i: int, v: u8) {
	assert(i >= 0 && i < 12288, "forest_depth: index out of range [0, 12288)")
	intrinsics.unaligned_store((^u8)(&o.data[o.base + 196608 + i * 1]), u8(v))
}

allocate :: proc() -> [^]u8 {
	raw, _ := mem.alloc(BYTE_SIZE, REGION_ALIGN)  // zero-initialized
	p := ([^]u8)(raw)
	return p
}
free_region :: proc(p: [^]u8) { free(p) }

NODE_SIZE :: 208960

Producer :: struct { ptr: [^]u8, input: u32 }
producer_from_raw :: proc(p: [^]u8) -> Producer { return Producer{p, 1} }
producer_write_slot :: proc(p: Producer) -> Forest { return Forest{data = p.ptr, base = ROOT_OFFSET + int(p.input) * NODE_SIZE} }
producer_commit :: proc(p: ^Producer) {
	old := intrinsics.atomic_exchange((^u32)(&p.ptr[0]), (p.input << 1) | u32(1))
	p.input = (old >> 1) & u32(3)
}
producer_free :: proc(p: Producer) { free(p.ptr) }

Consumer :: struct { ptr: [^]u8, output: u32 }
consumer_from_raw :: proc(p: [^]u8) -> Consumer { return Consumer{p, 2} }
consumer_has_new :: proc(c: Consumer) -> bool { return (intrinsics.atomic_load((^u32)(&c.ptr[0])) & u32(1)) != 0 }
consumer_read :: proc(c: ^Consumer) -> Forest {
	if (intrinsics.atomic_load((^u32)(&c.ptr[0])) & u32(1)) != 0 {
		old := intrinsics.atomic_exchange((^u32)(&c.ptr[0]), c.output << 1)
		c.output = (old >> 1) & u32(3)
	}
	return Forest{data = c.ptr, base = ROOT_OFFSET + int(c.output) * NODE_SIZE}
}
double_buffer :: proc() -> (Producer, Consumer) {
	p := allocate()
	return Producer{p, 1}, Consumer{p, 2}
}
